version: '3.9'

name: inception
services:
  mariadb:
    container_name: mariadb
    image: apigeon/mariadb
    build: 
      context: requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWD
      - MYSQL_USER
      - MYSQL_USER_PASSWD
      - MYSQL_DATABASE
      - MYSQL_GITEA_USER
      - MYSQL_GITEA_PASSWD
      - MYSQL_GITEA_DATABASE
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
  wordpress:
    container_name: wordpress
    image: apigeon/wordpress
    build: requirements/wordpress
    networks:
      - inception
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_USER_PASSWD
      - MYSQL_HOST=mariadb
      - NGINX_DOMAIN
      - WORDPRESS_ADMIN_USER
      - WORDPRESS_ADMIN_PASSWD
      - WORDPRESS_ADMIN_EMAIL
      - WORDPRESS_SITE_TITLE
      - WORDPRESS_AUTHOR
      - WORDPRESS_AUTHOR_EMAIL
      - WORDPRESS_AUTHOR_PASSWD
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
  nginx:
    container_name: nginx
    image: apigeon/nginx
    build:
      context: requirements/nginx
      args:
        - NGINX_DOMAIN
    networks:
      - inception
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress:ro
      - adminer:/var/www/adminer:ro
    depends_on:
      - wordpress
      - gitea
      - static
      - adminer
  # --- BONUS ---
  # ftp:
  #   container_name: ftp
  #   image: apigeon/ftp
  #   build:
  #     context: requirements/bonus/ftp
  #     args:
  #       - FTP_USER
  #       - FTP_PASSWD
  #   networks:
  #     - inception
  #   restart: unless-stopped
  #   ports:
  #     - 21:21
  #     - 2100-2110:2100-2110
  #   volumes:
  #     - wordpress:/var/www/wordpress
  #   depends_on:
  #     - wordpress
  redis:
    container_name: redis
    image: apigeon/redis
    build: requirements/bonus/redis
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - redis:/var/lib/redis
  adminer:
    container_name: adminer
    image: apigeon/adminer
    build: requirements/bonus/adminer
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - adminer:/var/www/adminer
    depends_on:
      mariadb:
        condition: service_healthy
  static:
    container_name: static
    image: apigeon/static
    build: requirements/bonus/static
    restart: unless-stopped
    networks:
      - inception
  gitea:
    container_name: gitea
    image: apigeon/gitea
    build: requirements/bonus/gitea
    environment:
      - MYSQL_GITEA_USER
      - MYSQL_GITEA_PASSWD
      - MYSQL_GITEA_DATABASE
      - MYSQL_HOST=mariadb
      - NGINX_DOMAIN
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - gitea:/var/lib/gitea
    depends_on:
      mariadb:
        condition: service_healthy
  # --- BONUS ---

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/$DATA_DIR/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/$DATA_DIR/wordpress
  redis:
    name: redis
  gitea:
    name: gitea
  adminer:
    name: adminer

networks:
  inception:
    driver: bridge
