version: '3'

name: inception
services:
  mariadb:
    container_name: mariadb
    image: apigeon/mariadb
    build: requirements/mariadb
    networks:
      - inception
    restart: always
    environment:
      - MARIADB_ROOT_PASSWD
      - WORDPRESS_DATABASE
      - WORDPRESS_USER
      - WORDPRESS_PASSWD
    # ports:
    #   - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
  wordpress:
    container_name: wordpress
    image: apigeon/wordpress
    build: requirements/wordpress
    networks:
      - inception
    restart: always
    # ports:
    #   - 9000:9000
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
  nginx:
    container_name: nginx
    image: apigeon/nginx
    build:
      context: requirements/nginx
      args:
        - DOMAIN
    networks:
      - inception
    restart: always
    ports:
      - 8080:443
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress

volumes:
  mariadb:
    name: mariadb
    driver: local
  wordpress:
    name: wordpress
    driver: local

networks:
  inception:
    driver: bridge