version: '3'

name: inception
services:
  mariadb:
    container_name: mariadb
    image: apigeon/mariadb
    build: 
      context: requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWD
        - MYSQL_USER
        - MYSQL_USER_PASSWD
        - MYSQL_DATABASE
        - MYSQL_GITEA_USER
        - MYSQL_GITEA_PASSWD
        - MYSQL_GITEA_DATABASE
    networks:
      - inception
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
  wordpress:
    container_name: wordpress
    image: apigeon/wordpress
    build: requirements/wordpress
    networks:
      - inception
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_USER_PASSWD
      - MYSQL_HOST=mariadb
      - WORDPRESS_ADMIN_USER
      - WORDPRESS_ADMIN_PASSWD
      - WORDPRESS_ADMIN_EMAIL
      - WORDPRESS_SITE_TITLE
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
      - redis
  nginx:
    container_name: nginx
    image: apigeon/nginx
    build:
      context: requirements/nginx
      args:
        - NGINX_DOMAIN
    networks:
      - inception
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
  # --- BONUS ---
  ftp:
    container_name: ftp
    image: apigeon/ftp
    build:
      context: requirements/bonus/ftp
      args:
        - FTP_USER
        - FTP_PASSWD
    networks:
      - inception
    restart: always
    ports:
      - 2121:21
      # - 2122-2221:2122-2221
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
  redis:
    container_name: redis
    image: apigeon/redis
    build: requirements/bonus/redis
    networks:
      - inception
    restart: always
    volumes:
      - redis:/var/lib/redis
  adminer:
    container_name: adminer
    image: apigeon/adminer
    build: requirements/bonus/adminer
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
      - wordpress
  static:
    container_name: static
    image: apigeon/static
    build: requirements/bonus/static
    restart: always
    networks:
      - inception
  gitea:
    container_name: gitea
    image: apigeon/gitea
    build: requirements/bonus/gitea
    environment:
      - MYSQL_GITEA_USER
      - MYSQL_GITEA_PASSWD
      - MYSQL_GITEA_DATABASE
      - MYSQL_HOST=mariadb
    restart: always
    networks:
      - inception
    ports:
      - 3000:3000
    volumes:
      - gitea:/var/lib/gitea
    depends_on:
      - mariadb
  # --- BONUS ---

volumes:
  mariadb:
    name: mariadb
    driver: local
  wordpress:
    name: wordpress
    driver: local
  redis:
    name: redis
    driver: local
  gitea:
    name: gitea
    driver: local

networks:
  inception:
    driver: bridge