version: '3'

name: inception
services:
  mariadb:
    container_name: mariadb
    image: apigeon/mariadb
    build: requirements/mariadb
    networks:
      - inception
    restart: always
    environment:
      - MARIADB_ROOT_PASSWD
      - WORDPRESS_DATABASE
      - WORDRESS_USER
      - WORDPRESS_PASSWD
    volumes:
      - mariadb:/var/lib/mysql
  wordpress:
    container_name: wordpress
    image: apigeon/wordpress
    build: requirements/wordpress
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb

volumes:
  mariadb:
    name: mariadb
    driver: local
  wordpress:
    name: wordpress
    driver: local

networks:
  inception:
    driver: bridge